name = "mcp-durable-object-repro"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = "nodejs_compat"

[vars]
OPENAI_API_KEY = "your-api-key-here"

[[durable_objects.bindings]]
name = "AgentDurableObject"
class_name = "AgentDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["AgentDurableObject"]
