name = "mcp-workers-bug"
main = "src/index.ts"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
OPENAI_API_KEY = "your-api-key-here"

[[durable_objects.bindings]]
name = "TestAgent"
class_name = "TestAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TestAgent"]
